In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [6]:
!pip install --upgrade numpy

  Using cached numpy-1.19.4-cp37-cp37m-win_amd64.whl (12.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [9]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np

print(np.__version__)

1.18.1


In [21]:
b = np.arange(20).reshape(4, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
b.dtype.name

'int32'

In [22]:

b.shape

(4, 5)

In [25]:
b.ndim

2

In [69]:
b.itemsize

4

In [29]:
b.size

20

In [31]:
type(b)

numpy.ndarray

In [35]:
b = np.array([2, 4, 8])
b

array([2, 4, 8])

In [36]:
type(b)

numpy.ndarray

In [37]:
a.flags.writeable

True

In [38]:
y = np.array([[3, 1, 7],
              [2, 0, 0],
              [8, 5, 9]])
y

array([[3, 1, 7],
       [2, 0, 0],
       [8, 5, 9]])

In [39]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
x = np.array([1, 3, 4])
x.shape

(3,)

In [71]:
y = np.zeros((2, 3, 4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [72]:
y.shape = (3, 8)
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:

y = np.reshape(np.arange(2*3*4), (2,3,4))
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
y.strides

(48, 16, 4)

In [46]:
 x= np.array([1, 2, 3])
x.ndim

1

In [47]:
y = np.zeros((2, 3, 4))
y.ndim

3

In [48]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
x.size

30

In [49]:
np.prod(x.shape)

30

In [50]:
x = np.array([1,2,3], dtype=np.float64)
x.itemsize

8

In [51]:
x = np.zeros((3,5,2), dtype=np.complex128)
x.nbytes

480

In [52]:
np.prod(x.shape) * x.itemsize

480

In [53]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [54]:
x.T

array([[1., 3.],
       [2., 4.]])

In [55]:
x = np.array([1.,2.,3.,4.])
x

array([1., 2., 3., 4.])

In [56]:
x = np.sqrt([1+0j, 0+1j])
x.real

array([1.        , 0.70710678])

In [57]:
x.real.dtype

dtype('float64')

In [58]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [60]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

In [61]:
import ctypes
x = np.array([[0, 1], [2, 3]], dtype=np.int32)
x

array([[0, 1],
       [2, 3]])

In [62]:
x.ctypes.data

1992148590400

In [63]:
np.random.seed(123)
x = np.random.randint(9, size=(3, 3))
x

array([[2, 2, 6],
       [1, 3, 6],
       [1, 0, 1]])

In [64]:

x = np.array([[0, 1], [2, 3]], dtype='<u2')
x.tobytes()

b'\x00\x00\x01\x00\x02\x00\x03\x00'

In [65]:
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [66]:
x.astype(int)

array([1, 2, 2])