In [1]:
import numpy as np

In [39]:
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    #x =  # Write your code here 
    x = np.arange(1,13).reshape(6, 2)
    return x

In [41]:
function1()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [141]:
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be start from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    # x =np.arange(10,90).reshape(3,3, 3)
    
    x = np.arange(10,37)
    newarr = x.reshape(3,3, 3)
    arr = newarr.astype('float64') 
    print(arr.dtype) 
    return arr

In [142]:
function2()

float64


array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [307]:
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = a[ (a % 5 == 0) & (a % 7 == 0 )] #wrtie your code here
    return x

In [308]:
function3()

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [163]:
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
    print("Original array:")
    print(arr)
    print("\nAfter swapping arrays:")
    arr[:,[1, 2]] = arr[:,[2, 1]]
    return arr

In [164]:
function4()

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After swapping arrays:


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [167]:
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = np.zeros(20).reshape(4,5)
  
    return z

In [168]:
function5()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [203]:
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr = np.zeros(10)
    arr[5,]=10
    arr[8,]=20
    return arr

In [204]:
function6()

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

In [213]:
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
    x[1:4,]=0
    return x


In [214]:
function7()

array([0, 0, 0, 0], dtype=int64)

In [222]:
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = np.arange(10 ).reshape(2,5)
    x[0:4,]=6
    return x


In [223]:
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [236]:
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a = np.arange(2, 102, 2)
  
    return a

In [237]:
function9()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [248]:
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt =arr- brr[:,None]
  
    return subt

In [249]:
function10()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [464]:
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = np.where(arr%2==1,"-1",arr)
  
    return ans


In [465]:
function11()

array(['0', '-1', '2', '-1', '4', '-1', '6', '-1', '8', '-1'],
      dtype='<U11')

In [286]:
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.stack((arr[0],arr[0],arr[0],arr[1],arr[1],arr[1],arr[2],arr[2],arr[2], ), axis = 0) 
  
    return ans

In [287]:
function12()

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [377]:
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = np.where(arr<5 ,4,arr)
  
    return ans

In [378]:
function13()

array([ 4,  6,  4,  9, 10,  4, 27])

In [460]:
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element
    #is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
    arr = np.arange(10, 34, 1).reshape(8,3)
   #e 
  
    return arr

In [461]:
function14()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [328]:
def function15():
    #Sort following NumPy array by the second column
    
    
    arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
   # ans = #write your code here 
    #arr[:,[1, 2]] = arr[:,[2, 1]]
    arr[[0,1],:]= arr[[1,0],:]
    return arr

In [329]:
function15()

array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [358]:
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    ans = np.array([y ,x])
  
    return ans


In [360]:
function16()

array([[[2],
        [3],
        [4]],

       [[1],
        [2],
        [3]]])

In [367]:
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    return     np.where(arr%(3*5) ==0,"yes",'No')

In [368]:
function17()

array([['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']],
      dtype='<U3')

In [406]:
def function18():
    # count values of "students" are exist in "piaic"
    piaic = np.arange(100)
    students = np.array([5,20,50,200,301,7001])
    x=np.where(students<=100,students.size,"")
    return x

In [407]:
function18()

array(['6', '6', '6', '', '', ''], dtype='<U11')

In [445]:
def function19():
    #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

    X =   np.arange(1,26).reshape(5,5)
    W=X.T
    b=5
    output =  (X*W)+b
    return output

In [446]:
function19()

array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])

In [452]:
def fucntion20():
    #apply fuction "abc" on each value of Array "X"
    x = np.arange(1,11)
    def xyz(x):
        return x*2+3-2
    return xyz(x)

In [453]:
fucntion20()

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])